package view;

import controller.HomeController;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.Date;
import javax.swing.JFileChooser;
import model.PinjamModel;


/**
 *
 * @author Faruq
 */
public class Home extends javax.swing.JPanel {
    private final PinjamModel pinjamModel;
    private final HomeController controller;
    
    public Home() {
        initComponents();
        pinjamModel = new PinjamModel();
        controller = new HomeController(this);
        gedungComboBox.addItem(null);
        gedungComboBox.addItem("2");
        gedungComboBox.addItem("3");
        
        gedungComboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.updateLantaiOptions();
            }
        });

        lantaiComboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.updateRuanganOptions();
            }
        });

        tanggalDateChooser.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if ("date".equals(evt.getPropertyName())) {
                    controller.filterTable();
                }
            }
        });

        lantaiComboBox.removeAllItems();
        ruanganComboBox.removeAllItems();
        controller.filterTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pinjamTable = new javax.swing.JTable();
        unduhTabelButton = new javax.swing.JButton();
        filterLabel = new javax.swing.JLabel();
        tanggalDateChooser = new com.toedter.calendar.JDateChooser();
        gedungComboBox = new javax.swing.JComboBox<>();
        lantaiComboBox = new javax.swing.JComboBox<>();
        ruanganComboBox = new javax.swing.JComboBox<>();
        tampilButton = new javax.swing.JButton();
        cariButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(27, 68, 156));
        setPreferredSize(new java.awt.Dimension(828, 433));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(4520, 402));

        pinjamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Tgl. Pinjam", "Gedung", "Lantai", "Ruangan", "Jam (Sesi)", "Kegiatan", "Peminjam", "Tgl. Pengajuan"
            }
        ));
        jScrollPane1.setViewportView(pinjamTable);

        unduhTabelButton.setBackground(new java.awt.Color(180, 232, 0));
        unduhTabelButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        unduhTabelButton.setText("Unduh Tabel");
        unduhTabelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unduhTabelButtonActionPerformed(evt);
            }
        });

        filterLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        filterLabel.setForeground(new java.awt.Color(255, 255, 255));
        filterLabel.setText("Filter :");

        tanggalDateChooser.setBackground(new java.awt.Color(255, 255, 255));
        tanggalDateChooser.setDateFormatString("yyyy-MM-dd");

        gedungComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gedungComboBoxActionPerformed(evt);
            }
        });

        lantaiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lantaiComboBoxActionPerformed(evt);
            }
        });

        tampilButton.setBackground(new java.awt.Color(232, 159, 39));
        tampilButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tampilButton.setText("Cari semua");
        tampilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilButtonActionPerformed(evt);
            }
        });

        cariButton.setBackground(new java.awt.Color(232, 159, 39));
        cariButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cariButton.setText("Cari");
        cariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(filterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanggalDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gedungComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lantaiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ruanganComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cariButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tampilButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(unduhTabelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(unduhTabelButton)
                        .addComponent(gedungComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lantaiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ruanganComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tampilButton)
                        .addComponent(cariButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(filterLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tanggalDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public PinjamModel getPinjamModel() {
        return pinjamModel;
    }

    public javax.swing.JComboBox<String> getGedungComboBox() {
        return gedungComboBox;
    }

    public javax.swing.JComboBox<String> getLantaiComboBox() {
        return lantaiComboBox;
    }

    public javax.swing.JComboBox<String> getRuanganComboBox() {
        return ruanganComboBox;
    }

    public com.toedter.calendar.JDateChooser getTanggalDateChooser() {
        return tanggalDateChooser;
    }

    public javax.swing.JTable getPinjamTable() {
        return pinjamTable;
    }
    
    private void populateComboBoxes() {
        gedungComboBox.addItem(null);
        gedungComboBox.addItem("2");
        gedungComboBox.addItem("3");
    }
    
    private void populatePinjamTable() {
        Date tanggal = tanggalDateChooser.getDate();
        String gedung = (String) gedungComboBox.getSelectedItem();
        String lantai = (String) lantaiComboBox.getSelectedItem();
        String ruangan = (String) ruanganComboBox.getSelectedItem();

        pinjamModel.populatePinjamTable(pinjamTable, tanggal, gedung, lantai, ruangan);
    }
    

    private void unduhTabelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unduhTabelButtonActionPerformed
        Object[] options = {"PDF", "CSV"};
        int choice = JOptionPane.showOptionDialog(this, 
                "Pilih format unduhan:", 
                "Unduh Tabel", 
                JOptionPane.DEFAULT_OPTION, 
                JOptionPane.INFORMATION_MESSAGE, 
                null, options, options[0]);

        if (choice == 0) {
            unduhSebagaiPDF();
        } else if (choice == 1) {
            unduhSebagaiCSV();
        }
    }//GEN-LAST:event_unduhTabelButtonActionPerformed

    private void gedungComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gedungComboBoxActionPerformed
        controller.updateLantaiOptions();
    }//GEN-LAST:event_gedungComboBoxActionPerformed

    private void lantaiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lantaiComboBoxActionPerformed
        controller.updateRuanganOptions();
    }//GEN-LAST:event_lantaiComboBoxActionPerformed

    private void tampilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilButtonActionPerformed
        tanggalDateChooser.setDate(null);
        gedungComboBox.setSelectedIndex(-1);
        lantaiComboBox.setSelectedIndex(-1);
        ruanganComboBox.setSelectedIndex(-1);

        controller.filterTable();
    }//GEN-LAST:event_tampilButtonActionPerformed

    private void cariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariButtonActionPerformed
        controller.filterTable();
    }//GEN-LAST:event_cariButtonActionPerformed
   
    private void unduhSebagaiPDF() {
        JFileChooser fileChooser = new JFileChooser();
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath() + ".pdf";
            pinjamModel.generatePDF(pinjamTable, filePath);
        }
    }

    private void unduhSebagaiCSV() {
        JFileChooser fileChooser = new JFileChooser();
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath() + ".csv";
            pinjamModel.generateCSV(pinjamTable, filePath);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cariButton;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JComboBox<String> gedungComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> lantaiComboBox;
    private javax.swing.JTable pinjamTable;
    private javax.swing.JComboBox<String> ruanganComboBox;
    private javax.swing.JButton tampilButton;
    private com.toedter.calendar.JDateChooser tanggalDateChooser;
    private javax.swing.JButton unduhTabelButton;
    // End of variables declaration//GEN-END:variables
}
