package view;

import javax.swing.JOptionPane;
import controller.PinjamController;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author Faruq
 */
public class Pinjam extends javax.swing.JPanel {
    private PinjamController controller;    
    /**
     * Creates new form Home
     */
    public Pinjam() {
        initComponents();
        controller = new PinjamController(this);
        gedungComboBox.addItem(null);
        gedungComboBox.addItem("2");
        gedungComboBox.addItem("3");
    }

    public JButton getUnduhButton() {
        return unduhButton;
    }

    public JComboBox<String> getLantaiComboBox() {
        return lantaiComboBox;
    }

    public JComboBox<String> getRuanganComboBox() {
        return ruanganComboBox;
    }

    public JComboBox<String> getGedungComboBox() {
        return gedungComboBox;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel15 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        judulLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        peminjamField = new javax.swing.JTextField();
        peminjamLabel = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        kegiatanField = new javax.swing.JTextField();
        kegiatanLabel = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        gedungLabel = new javax.swing.JLabel();
        gedungComboBox = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        lantaiLabel = new javax.swing.JLabel();
        lantaiComboBox = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        ruanganLabel = new javax.swing.JLabel();
        ruanganComboBox = new javax.swing.JComboBox<>();
        jPanel17 = new javax.swing.JPanel();
        ruanganLabel1 = new javax.swing.JLabel();
        tanggalDateChooser = new com.toedter.calendar.JDateChooser();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        sesi1CheckBox = new javax.swing.JCheckBox();
        sesi3CheckBox = new javax.swing.JCheckBox();
        jPanel19 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        sesi2CheckBox = new javax.swing.JCheckBox();
        sesi4CheckBox = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        setujuCheckBox = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        unduhButton = new javax.swing.JButton();
        gapLabel1 = new javax.swing.JLabel();
        ajukanButton = new javax.swing.JButton();
        gapLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();

        jFormattedTextField1.setText("jFormattedTextField1");

        jPanel15.setBackground(new java.awt.Color(232, 159, 39));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 0));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 50));

        judulLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        judulLabel1.setText("Formulir Peminjaman");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(judulLabel1)
                .addGap(78, 78, 78))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(judulLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel6.setLayout(new java.awt.BorderLayout(4, 4));
        jPanel6.add(peminjamField, java.awt.BorderLayout.CENTER);

        peminjamLabel.setText("Peminjam :");
        jPanel6.add(peminjamLabel, java.awt.BorderLayout.LINE_START);

        jPanel5.add(jPanel6);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel11.setLayout(new java.awt.BorderLayout(4, 4));
        jPanel11.add(kegiatanField, java.awt.BorderLayout.CENTER);

        kegiatanLabel.setText("Kegiatan  : ");
        jPanel11.add(kegiatanLabel, java.awt.BorderLayout.LINE_START);

        jPanel5.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel12.setLayout(new java.awt.BorderLayout(4, 4));

        gedungLabel.setText("Gedung    : ");
        jPanel12.add(gedungLabel, java.awt.BorderLayout.LINE_START);

        gedungComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gedungComboBoxActionPerformed(evt);
            }
        });
        jPanel12.add(gedungComboBox, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel13.setLayout(new java.awt.BorderLayout(4, 4));

        lantaiLabel.setText("Lantai       : ");
        jPanel13.add(lantaiLabel, java.awt.BorderLayout.LINE_START);

        lantaiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lantaiComboBoxActionPerformed(evt);
            }
        });
        jPanel13.add(lantaiComboBox, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel14.setLayout(new java.awt.BorderLayout(4, 4));

        ruanganLabel.setText("Ruangan   : ");
        jPanel14.add(ruanganLabel, java.awt.BorderLayout.LINE_START);
        jPanel14.add(ruanganComboBox, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel14);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel17.setLayout(new java.awt.BorderLayout(4, 4));

        ruanganLabel1.setText("Tanggal    : ");
        jPanel17.add(ruanganLabel1, java.awt.BorderLayout.LINE_START);
        jPanel17.add(tanggalDateChooser, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel17);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Jam           :  ");
        jPanel8.add(jLabel2, java.awt.BorderLayout.WEST);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        sesi1CheckBox.setText("Sesi 1");

        sesi3CheckBox.setText("Sesi 3");
        sesi3CheckBox.setPreferredSize(new java.awt.Dimension(32, 20));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel18Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(sesi1CheckBox)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(sesi3CheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel18Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sesi1CheckBox)
                        .addComponent(sesi3CheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel8.add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel8);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel19.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("                     ");
        jPanel19.add(jLabel3, java.awt.BorderLayout.WEST);

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));

        sesi2CheckBox.setText("Sesi 2");

        sesi4CheckBox.setText("Sesi 4");
        sesi4CheckBox.setPreferredSize(new java.awt.Dimension(32, 20));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel20Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(sesi2CheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(sesi4CheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel20Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sesi2CheckBox)
                        .addComponent(sesi4CheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel19.add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel19);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(400, 20));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel7);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel10.setLayout(new java.awt.BorderLayout());

        setujuCheckBox.setText("Saya menyetujui aturan yang berlaku");
        setujuCheckBox.setPreferredSize(new java.awt.Dimension(378, 40));
        jPanel10.add(setujuCheckBox, java.awt.BorderLayout.WEST);

        jPanel5.add(jPanel10);

        jPanel1.add(jPanel5);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        unduhButton.setBackground(new java.awt.Color(180, 232, 0));
        unduhButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        unduhButton.setText("Unduh");
        unduhButton.setPreferredSize(new java.awt.Dimension(75, 30));
        unduhButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unduhButtonActionPerformed(evt);
            }
        });
        jPanel9.add(unduhButton, new java.awt.GridBagConstraints());

        gapLabel1.setText("    ");
        jPanel9.add(gapLabel1, new java.awt.GridBagConstraints());

        ajukanButton.setBackground(new java.awt.Color(27, 68, 156));
        ajukanButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ajukanButton.setForeground(new java.awt.Color(255, 255, 255));
        ajukanButton.setText("Ajukan");
        ajukanButton.setPreferredSize(new java.awt.Dimension(75, 30));
        ajukanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajukanButtonActionPerformed(evt);
            }
        });
        jPanel9.add(ajukanButton, new java.awt.GridBagConstraints());

        gapLabel.setText("    ");
        jPanel9.add(gapLabel, new java.awt.GridBagConstraints());

        deleteButton.setBackground(new java.awt.Color(255, 0, 39));
        deleteButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Hapus");
        deleteButton.setPreferredSize(new java.awt.Dimension(75, 30));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel9.add(deleteButton, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel9);

        jPanel2.setBackground(new java.awt.Color(27, 68, 156));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Peraturan Peminjaman Ruangan");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("1. Peminjaman ruangan dilakukan minimal 1 hari sebelum tanggal kegiatan.");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("2. Ruangan hanya digunakan pada hari kerja (Senin - Minggu),");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("3. Ruangan harus digunakan sesuai dengan tujuan permohonan.");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("4. Dilarang mengubah tata letak atau fasilitas ruangan tanpa izin.");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("    keterangan: Sesi 1: 07.20 - 09.50 WIB, Sesi 2: 10.00 - 12.40 WIB,");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("5. Peminjam bertanggung jawab untuk menjaga kebersihan");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("    dan kerapihan ruangan selama dan setelah pemakaian.");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("                        Sesi 3: 13.30 - 16.00 WIB, Sesi 4: 16.00 - 18.00 WIB.");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("6. Peminjam bertanggung jawab atas segala kerusakan atau kehilangan");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("    fasilitas yang terjadi selama pemakaian.");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("6. Peminjam bertanggung jawab atas segala kerusakan atau kehilangan");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("    fasilitas yang terjadi selama pemakaian.");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("    dikenakan sanksi penambahan poin pelanggaran dan/atau denda.");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("7. Pelanggaran terhadap peraturan peminjaman ruangan dapat");

        jPanel16.setBackground(new java.awt.Color(232, 159, 39));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap(54, Short.MAX_VALUE))
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ajukanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajukanButtonActionPerformed
        String peminjam = peminjamField.getText();
        String kegiatan = kegiatanField.getText();
        String gedung = gedungComboBox.getSelectedItem().toString();
        String lantai = lantaiComboBox.getSelectedItem().toString();
        String ruangan = ruanganComboBox.getSelectedItem().toString();
        Date tanggal = tanggalDateChooser.getDate();
        
        ArrayList<String> jamList = new ArrayList<>();
        if (sesi1CheckBox.isSelected()) {
            jamList.add("1");
        }
        if (sesi2CheckBox.isSelected()) {
            jamList.add("2");
        }
        if (sesi3CheckBox.isSelected()) {
            jamList.add("3");
        }
        if (sesi4CheckBox.isSelected()) {
            jamList.add("4");
        }

        String jam = String.join(", ", jamList);
        
        if (validateForm(peminjam, kegiatan, gedung, lantai, ruangan, tanggal, jam)) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String tanggalString = dateFormat.format(tanggal); 

            controller.processPeminjaman(peminjam, kegiatan, gedung, lantai, ruangan, tanggalString, jam);
        }
    }//GEN-LAST:event_ajukanButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        peminjamField.setText("");
        kegiatanField.setText("");
        gedungComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void unduhButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unduhButtonActionPerformed
        controller.unduhSuratPeminjaman();
    }//GEN-LAST:event_unduhButtonActionPerformed

    private void gedungComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gedungComboBoxActionPerformed
        controller.updateLantaiOptions();
    }//GEN-LAST:event_gedungComboBoxActionPerformed

    private void lantaiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lantaiComboBoxActionPerformed
        controller.updateRuanganOptions();
    }//GEN-LAST:event_lantaiComboBoxActionPerformed

    private void updateLantaiOptions() {
        lantaiComboBox.removeAllItems();
        ruanganComboBox.removeAllItems();

        String selectedGedung = (String) gedungComboBox.getSelectedItem();
        if (selectedGedung != null) {
            switch (selectedGedung) {
                case "2":
                    lantaiComboBox.addItem("1");
                    lantaiComboBox.addItem("5");
                    lantaiComboBox.addItem("6");
                    break;
                case "3":
                    lantaiComboBox.addItem("2");
                    lantaiComboBox.addItem("3");
                    lantaiComboBox.addItem("4");
                    break;
            }
        }
    }

    private void updateRuanganOptions() {
        ruanganComboBox.removeAllItems();

        String selectedGedung = (String) gedungComboBox.getSelectedItem();
        String selectedLantai = (String) lantaiComboBox.getSelectedItem();

        if (selectedGedung != null && selectedLantai != null) {
            if (selectedGedung.equals("2")) {
                switch (selectedLantai) {
                    case "1":
                        ruanganComboBox.addItem("Auditorium");
                        break;
                    case "5":
                        ruanganComboBox.addItem("251");
                        ruanganComboBox.addItem("252");
                        ruanganComboBox.addItem("253");
                        ruanganComboBox.addItem("254");
                        ruanganComboBox.addItem("256");
                        ruanganComboBox.addItem("257");
                        ruanganComboBox.addItem("258");
                        break;
                    case "6":
                        ruanganComboBox.addItem("261");
                        ruanganComboBox.addItem("262");
                        ruanganComboBox.addItem("263");
                        ruanganComboBox.addItem("264");
                        ruanganComboBox.addItem("266");
                        ruanganComboBox.addItem("267");
                        ruanganComboBox.addItem("268");
                        break;
                }
            } else if (selectedGedung.equals("3")) {
                switch (selectedLantai) {
                    case "2":
                        ruanganComboBox.addItem("321");
                        ruanganComboBox.addItem("322");
                        ruanganComboBox.addItem("323");
                        ruanganComboBox.addItem("324");
                        ruanganComboBox.addItem("326");
                        ruanganComboBox.addItem("327");
                        ruanganComboBox.addItem("328");
                        break;
                    case "3":
                        ruanganComboBox.addItem("331");
                        ruanganComboBox.addItem("332");
                        ruanganComboBox.addItem("333");
                        ruanganComboBox.addItem("334");
                        ruanganComboBox.addItem("336");
                        ruanganComboBox.addItem("337");
                        ruanganComboBox.addItem("338");
                        break;
                    case "4":
                        ruanganComboBox.addItem("341");
                        ruanganComboBox.addItem("342");
                        ruanganComboBox.addItem("343");
                        ruanganComboBox.addItem("344");
                        ruanganComboBox.addItem("346");
                        ruanganComboBox.addItem("347");
                        ruanganComboBox.addItem("348");
                        break;
                }
            }
        }
    }
    
    private boolean validateForm(String peminjam, String kegiatan, String gedung, String lantai, String ruangan, Date tanggal, String jam) {
        ArrayList<String> missingFields = new ArrayList<>();

        if (peminjam.isEmpty()) missingFields.add("Peminjam");
        if (kegiatan.isEmpty()) missingFields.add("Kegiatan");
        if (gedung.isEmpty()) missingFields.add("Gedung");
        if (lantai.isEmpty()) missingFields.add("Lantai");
        if (ruangan.isEmpty()) missingFields.add("Ruangan");
        if (tanggal == null) missingFields.add("Tanggal");
        if (jam.isEmpty()) missingFields.add("Jam");

        if (!missingFields.isEmpty()) {
            if (missingFields.size() == 7) {
                JOptionPane.showMessageDialog(this, "Silakan isi semua isian formulir!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                String message = "Dimohon isi bagian: " + String.join(", ", missingFields) + "!";
                JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
            }
            return false;
        }

        if (!setujuCheckBox.isSelected()) {
            JOptionPane.showMessageDialog(this, "Dimohon untuk menyetujui aturan yang berlaku", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajukanButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel gapLabel;
    private javax.swing.JLabel gapLabel1;
    private javax.swing.JComboBox<String> gedungComboBox;
    private javax.swing.JLabel gedungLabel;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel judulLabel1;
    private javax.swing.JTextField kegiatanField;
    private javax.swing.JLabel kegiatanLabel;
    private javax.swing.JComboBox<String> lantaiComboBox;
    private javax.swing.JLabel lantaiLabel;
    private javax.swing.JTextField peminjamField;
    private javax.swing.JLabel peminjamLabel;
    private javax.swing.JComboBox<String> ruanganComboBox;
    private javax.swing.JLabel ruanganLabel;
    private javax.swing.JLabel ruanganLabel1;
    private javax.swing.JCheckBox sesi1CheckBox;
    private javax.swing.JCheckBox sesi2CheckBox;
    private javax.swing.JCheckBox sesi3CheckBox;
    private javax.swing.JCheckBox sesi4CheckBox;
    private javax.swing.JCheckBox setujuCheckBox;
    private com.toedter.calendar.JDateChooser tanggalDateChooser;
    private javax.swing.JButton unduhButton;
    // End of variables declaration//GEN-END:variables
}